backend:
  name: github
  repo: calco/calco.com.br
  branch: main
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "artigos"
    label: "Artigos"
    folder: "artigos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Verificado", name: "verificado", widget: "boolean", default: true}
      - {label: "Selo", name: "selo", widget: "string", default: "✓ Conteúdo Auditado Calco"}
      - {label: "Corpo", name: "body", widget: "markdown"}
